#!/usr/bin/env bash

# Update package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Start the Nginx service
service nginx start

# Create a simple "Hello World!" index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirection for a specific URL
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Test the Nginx configuration for syntax errors
sudo nginx -t

# If the test passes without errors, restart Nginx to apply the changes
service nginx restart
    
