#!/usr/bin/env bash
# Install and configure HAproxy on my load balancer

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend Akindele-frontend
        bind *:80
        mode http
        default_backend Akindele-backend

backend Akindele-backend
        balance roundrobin
        server 290618-web-01 54.165.175.215:80 check
        server 290618-web-02 35.153.93.54:80 check
EOT
# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
