#!/usr/bin/env bash
# Bash script to display the content of /etc/passwd with specific fields

while IFS=':' read -r username _ userid _ homedir _; do
  echo "$username:$userid:$homedir"
done < /etc/passwd
