#!/usr/bin/env bash
#Display the content of the current directory in a list format,
#showing only the part of the name after the first dash

for file in *; do
  if [[ -f $file && ! $file == .* ]]; then
    name=$(echo "$file" | cut -d'-' -f2-)
    echo "$name"
  fi
done
