#!/bin/bash
# Generate an RSA key pair with the specified parameters
# Output confirmation
ssh-keygen -t rsa -b 4096 -C "vagrant@ubuntu" -N "betty" -f school
echo "RSA key pair 'school' created successfully!"
